[package]
name = "lhauspie/fibo"
version = "1.0.0"
description = "Calculates the fibonacci number of n : Fn"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lhauspie/wasm-fibo"
homepage = "https://github.com/lhauspie/wasm-fibo"
disable-command-rename = false

[[module]]
name = "fibo"
source = "target/fibo.wasm"
abi = "wasi"

[[command]]
name = "fibo"
module = "fibo"
